export const emojisBandeirasPaises = {
  Afeganistão: "🇦🇫",
  "África do Sul": "🇿🇦",
  Albânia: "🇦🇱",
  Alemanha: "🇩🇪",
  Andorra: "🇦🇩",
  Angola: "🇦🇴",
  Anguilla: "🇦🇮",
  "Antígua e Barbuda": "🇦🇬",
  "Arábia Saudita": "🇸🇦",
  Argélia: "🇩🇿",
  Argentina: "🇦🇷",
  Armênia: "🇦🇲",
  Aruba: "🇦🇼",
  Austrália: "🇦🇺",
  Áustria: "🇦🇹",
  Azerbaijão: "🇦🇿",
  Bahamas: "🇧🇸",
  Bahrein: "🇧🇭",
  Bangladesh: "🇧🇩",
  Barbados: "🇧🇧",
  Belarus: "🇧🇾",
  Bélgica: "🇧🇪",
  Belize: "🇧🇿",
  Benin: "🇧🇯",
  Bermudas: "🇧🇲",
  Butão: "🇧🇹",
  Bolívia: "🇧🇴",
  "Bósnia e Herzegovina": "🇧🇦",
  Botsuana: "🇧🇼",
  Brasil: "🇧🇷",
  Brunei: "🇧🇳",
  Bulgária: "🇧🇬",
  "Burkina Faso": "🇧🇫",
  Burundi: "🇧🇮",
  "Cabo Verde": "🇨🇻",
  Camarões: "🇨🇲",
  Camboja: "🇰🇭",
  Canadá: "🇨🇦",
  Catar: "🇶🇦",
  Cazaquistão: "🇰🇿",
  Chade: "🇹🇩",
  Chile: "🇨🇱",
  China: "🇨🇳",
  Chipre: "🇨🇾",
  Colômbia: "🇨🇴",
  Comores: "🇰🇲",
  Congo: "🇨🇬",
  "Coreia do Norte": "🇰🇵",
  "Coreia do Sul": "🇰🇷",
  "Costa do Marfim": "🇨🇮",
  "Costa Rica": "🇨🇷",
  Croácia: "🇭🇷",
  Cuba: "🇨🇺",
  Curaçao: "🇨🇼",
  Dinamarca: "🇩🇰",
  Djibouti: "🇩🇯",
  Dominica: "🇩🇲",
  Egito: "🇪🇬",
  "El Salvador": "🇸🇻",
  "Emirados Árabes Unidos": "🇦🇪",
  Equador: "🇪🇨",
  Eritreia: "🇪🇷",
  Eslováquia: "🇸🇰",
  Eslovênia: "🇸🇮",
  Espanha: "🇪🇸",
  Essuatíni: "🇸🇿",
  "Estados Unidos": "🇺🇸",
  Estônia: "🇪🇪",
  Etiópia: "🇪🇹",
  Fiji: "🇫🇯",
  Filipinas: "🇵🇭",
  Finlândia: "🇫🇮",
  França: "🇫🇷",
  Gabão: "🇬🇦",
  Gâmbia: "🇬🇲",
  Gana: "🇬🇭",
  Geórgia: "🇬🇪",
  Granada: "🇬🇩",
  Grécia: "🇬🇷",
  Groenlândia: "🇬🇱",
  Guadalupe: "🇬🇵",
  Guam: "🇬🇺",
  Guatemala: "🇬🇹",
  Guiana: "🇬🇾",
  Guiné: "🇬🇳",
  "Guiné Equatorial": "🇬🇶",
  "Guiné-Bissau": "🇬🇼",
  Haiti: "🇭🇹",
  Honduras: "🇭🇳",
  "Hong Kong": "🇭🇰",
  Hungria: "🇭🇺",
  Iêmen: "🇾🇪",
  "Ilhas Cayman": "🇰🇾",
  "Ilhas Cook": "🇨🇰",
  "Ilhas Faroe": "🇫🇴",
  "Ilhas Malvinas": "🇫🇰",
  "Ilhas Marianas do Norte": "🇲🇵",
  "Ilhas Marshall": "🇲🇭",
  "Ilhas Salomão": "🇸🇧",
  "Ilhas Virgens Britânicas": "🇻🇬",
  "Ilhas Virgens Americanas": "🇻🇮",
  Índia: "🇮🇳",
  Indonésia: "🇮🇩",
  Irã: "🇮🇷",
  Iraque: "🇮🇶",
  Irlanda: "🇮🇪",
  Islândia: "🇮🇸",
  Israel: "🇮🇱",
  Itália: "🇮🇹",
  Jamaica: "🇯🇲",
  Japão: "🇯🇵",
  Jordânia: "🇯🇴",
  Kiribati: "🇰🇮",
  Kosovo: "🇽🇰",
  Kuwait: "🇰🇼",
  Laos: "🇱🇦",
  Lesoto: "🇱🇸",
  Letônia: "🇱🇻",
  Líbano: "🇱🇧",
  Libéria: "🇱🇷",
  Líbia: "🇱🇾",
  Liechtenstein: "🇱🇮",
  Lituânia: "🇱🇹",
  Luxemburgo: "🇱🇺",
  Macau: "🇲🇴",
  "Macedônia do Norte": "🇲🇰",
  Madagascar: "🇲🇬",
  Malásia: "🇲🇾",
  Malauí: "🇲🇼",
  Maldivas: "🇲🇻",
  Mali: "🇲🇱",
  Malta: "🇲🇹",
  Marrocos: "🇲🇦",
  Martinica: "🇲🇶",
  Maurícia: "🇲🇺",
  Mauritânia: "🇲🇷",
  México: "🇲🇽",
  Micronésia: "🇫🇲",
  Moçambique: "🇲🇿",
  Moldávia: "🇲🇩",
  Mônaco: "🇲🇨",
  Mongólia: "🇲🇳",
  Montenegro: "🇲🇪",
  Montserrat: "🇲🇸",
  Mianmar: "🇲🇲",
  Namíbia: "🇳🇦",
  Nauru: "🇳🇷",
  Nepal: "🇳🇵",
  Nicarágua: "🇳🇮",
  Níger: "🇳🇪",
  Nigéria: "🇳🇬",
  Niue: "🇳🇺",
  Noruega: "🇳🇴",
  "Nova Caledônia": "🇳🇨",
  "Nova Zelândia": "🇳🇿",
  Omã: "🇴🇲",
  "Países Baixos": "🇳🇱",
  Palau: "🇵🇼",
  Palestina: "🇵🇸",
  Panamá: "🇵🇦",
  "Papua Nova Guiné": "🇵🇬",
  Paquistão: "🇵🇰",
  Paraguai: "🇵🇾",
  Peru: "🇵🇪",
  "Polinésia Francesa": "🇵🇫",
  Polônia: "🇵🇱",
  Portugal: "🇵🇹",
  Quênia: "🇰🇪",
  Quirguistão: "🇰🇬",
  "Reino Unido": "🇬🇧",
  "República Centro-Africana": "🇨🇫",
  "República Democrática do Congo": "🇨🇩",
  "República Dominicana": "🇩🇴",
  "República Tcheca": "🇨🇿",
  Romênia: "🇷🇴",
  Ruanda: "🇷🇼",
  Rússia: "🇷🇺",
  "Saara Ocidental": "🇪🇭",
  Samoa: "🇼🇸",
  "Samoa Americana": "🇦🇸",
  "San Marino": "🇸🇲",
  "Santa Helena": "🇸🇭",
  "Santa Lúcia": "🇱🇨",
  "São Bartolomeu": "🇧🇱",
  "São Cristóvão e Neves": "🇰🇳",
  "São Martinho (França)": "🇲🇫",
  "São Pedro e Miquelon": "🇵🇲",
  "São Tomé e Príncipe": "🇸🇹",
  "São Vicente e Granadinas": "🇻🇨",
  Seicheles: "🇸🇨",
  Senegal: "🇸🇳",
  "Serra Leoa": "🇸🇱",
  Sérvia: "🇷🇸",
  Singapura: "🇸🇬",
  Síria: "🇸🇾",
  Somália: "🇸🇴",
  "Sri Lanka": "🇱🇰",
  Suazilândia: "🇸🇿",
  Sudão: "🇸🇩",
  "Sudão do Sul": "🇸🇸",
  Suécia: "🇸🇪",
  Suíça: "🇨🇭",
  Suriname: "🇸🇷",
  Tailândia: "🇹🇭",
  Taiwan: "🇹🇼",
  Tanzânia: "🇹🇿",
  Tajiquistão: "🇹🇯",
  "Timor-Leste": "🇹🇱",
  Togo: "🇹🇬",
  Tonga: "🇹🇴",
  "Trinidad e Tobago": "🇹🇹",
  Tunísia: "🇹🇳",
  "Turcas e Caicos": "🇹🇨",
  Turcomenistão: "🇹🇲",
  Turquia: "🇹🇷",
  Tuvalu: "🇹🇻",
  Ucrânia: "🇺🇦",
  Uganda: "🇺🇬",
  Uruguai: "🇺🇾",
  Uzbequistão: "🇺🇿",
  Vanuatu: "🇻🇺",
  Vaticano: "🇻🇦",
  Venezuela: "🇻🇪",
  Vietnã: "🇻🇳",
  "Wallis e Futuna": "🇼🇫",
  Zâmbia: "🇿🇲",
  Zimbábue: "🇿🇼",
};

export const selecionarBandeiraPais = (pais) => {
  return emojisBandeirasPaises[pais] || "✨";
};
